/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package week3;

import com.google.gson.Gson;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.TextField;
import javafx.scene.control.Button;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

import java.util.Vector;


public class App extends Application {



    public App() {

    }
    @Override
    public void start(Stage stage) throws Exception {
        stage.setTitle("Course Generator");

        //Labels for all the entry fields
        Label departmentLabel = new Label("Department");
        Label crnLabel = new Label("Course Number");
        Label nameLabel = new Label("Course Name");
        Label creditLabel = new Label("Number of credits");

        //ChoiceBox (drop-down menu)
        ChoiceBox dropdown = new ChoiceBox();
        //Here are the options for the drop-down menu
        //CS CHEM PHYS MATH BTNY ZOO
        dropdown.getItems().add("CS");
        dropdown.getItems().add("CHEM");
        dropdown.getItems().add("PHYS");
        dropdown.getItems().add("MATH");
        dropdown.getItems().add("BTNY");
        dropdown.getItems().add("ZOO");

        //Text fields for the other instance variables in course: crn, name, and credit
        TextField crnEntry = new TextField();
        TextField nameEntry = new TextField();
        TextField creditEntry = new TextField();

        //This is a little HBox that will only display anything if there is an error
        HBox error_box = new HBox();

        //This is the vector object where we will store the courses
        Vector<Course> courseVector = new Vector<Course>(50);
        //This button will save and enter everything that has been entered
        Button enterbutton = new Button("Generate Course");

        //Here is enterbutton's event handler
        enterbutton.setOnAction(new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent generateCourse) {
                try {
                    //variables to be stored
                    String obj_department = (String) dropdown.getValue();
                    int obj_crn = Integer.parseInt(crnEntry.getText());
                    String obj_name = nameEntry.getText();
                    int obj_credit = Integer.parseInt(creditEntry.getText());

                    Course generatedCourse = new Course(obj_department, obj_crn, obj_name, obj_credit);
                    courseVector.add(generatedCourse);

                } catch (Exception badEntry) {
                    error_box.getChildren().clear();
                    Label errorLabel = new Label("Cannot generate a course with this data.");
                    error_box.getChildren().add(errorLabel);
                }
            }
        });

        //This display button goes to the right of the course maker fields and displays the courses in the vector
        Button displayallbutton = new Button("Display Courses");
        //VBox to put the new courses in
        VBox courseList = new VBox();
        //eventhandler to display the vecctor
        displayallbutton.setOnAction(new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent event) {
                courseList.getChildren().clear();
                for (Course courses: courseVector) {
                    Label courseLabel = new Label(courses.toString());
                    courseList.getChildren().add(courseLabel);
                }
            }
    });





        //Okay this vbox should hold all of the buttons for entering the data
        //Any errors will be displayed beneath this box
        VBox button_holder = new VBox(departmentLabel, dropdown, crnLabel,crnEntry, nameLabel,nameEntry,
                creditLabel,creditEntry, enterbutton, error_box);


        //This vbox is where we will display the generated courses
        VBox course_box = new VBox(displayallbutton, courseList);

        //This is the final box. We will only put button_holder in here for now, but we will probably add more later.
        HBox big_box = new HBox(button_holder, course_box);

        //Here is the final scene. Only big_box should be put in here with the dimensions.
        Scene biggest_box = new Scene(big_box, 500, 500);
        stage.setScene(biggest_box);

        stage.show();
    }



    public static void main(String[] args) {Application.launch(args);} //launches the boc
}
